"""baseline schema

Revision ID: c1aaf793328a
Revises: 
Create Date: 2026-03-09 10:37:10.658603

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision = 'c1aaf793328a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('channels',
    sa.Column('channel_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('channel_code', postgresql.ENUM('TELEGRAM', 'MAX', 'WEB', 'TEST_CONSOLE', 'UNKNOWN', name='channel_type_enum'), nullable=False),
    sa.Column('channel_name', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('channel_id', name=op.f('pk_channels')),
    sa.UniqueConstraint('channel_code', name=op.f('uq_channels_channel_code'))
    )
    op.create_table('ingestion_jobs',
    sa.Column('job_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.Text(), nullable=False),
    sa.Column('parser_version', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('job_id', name=op.f('pk_ingestion_jobs'))
    )
    op.create_index('idx_ingestion_jobs_file_hash', 'ingestion_jobs', ['file_hash'], unique=False)
    op.create_index('idx_ingestion_jobs_stage', 'ingestion_jobs', ['stage'], unique=False)
    op.create_index('idx_ingestion_jobs_started_at', 'ingestion_jobs', ['started_at'], unique=False)
    op.create_index('idx_ingestion_jobs_status', 'ingestion_jobs', ['status'], unique=False)
    op.create_table('quality_aggregates_daily',
    sa.Column('quality_aggregate_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('aggregate_date', sa.Date(), nullable=False),
    sa.Column('channel_code', postgresql.ENUM('TELEGRAM', 'MAX', 'WEB', 'TEST_CONSOLE', 'UNKNOWN', name='channel_type_enum'), server_default=sa.text("'UNKNOWN'"), nullable=False),
    sa.Column('intent_type', postgresql.ENUM('ELIGIBILITY_QUESTION', 'DOCUMENTS_QUESTION', 'REJECTION_QUESTION', 'FORM_QUESTION', 'DEADLINE_QUESTION', 'PAYMENT_TIMING_QUESTION', 'AMOUNT_QUESTION', 'PROCEDURE_QUESTION', 'APPEAL_QUESTION', 'MIXED_QUESTION', 'AMBIGUOUS_QUESTION', 'NO_MEASURE_DETECTED', 'OTHER', name='question_intent_enum'), server_default=sa.text("'OTHER'"), nullable=False),
    sa.Column('measure_code', sa.Text(), nullable=True),
    sa.Column('total_answers', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_feedback', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('avg_feedback_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('reused_answers_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('low_rated_answers_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('failed_validation_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('quality_aggregate_id', name=op.f('pk_quality_aggregates_daily')),
    sa.UniqueConstraint('aggregate_date', 'channel_code', 'intent_type', 'measure_code', name='uq_quality_aggregates_daily')
    )
    op.create_index('idx_quality_aggregates_daily_date', 'quality_aggregates_daily', ['aggregate_date'], unique=False)
    op.create_index('idx_quality_aggregates_daily_measure', 'quality_aggregates_daily', ['measure_code'], unique=False)
    op.create_table('conversation_sessions',
    sa.Column('session_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('external_session_id', sa.Text(), nullable=False),
    sa.Column('external_user_id', sa.Text(), nullable=True),
    sa.Column('external_chat_id', sa.Text(), nullable=True),
    sa.Column('user_platform_name', sa.Text(), nullable=True),
    sa.Column('session_started_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('session_last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], name=op.f('fk_conversation_sessions_channel_id_channels'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_conversation_sessions')),
    sa.UniqueConstraint('channel_id', 'external_session_id', name='uq_conversation_sessions_unique')
    )
    op.create_index('idx_conversation_sessions_channel', 'conversation_sessions', ['channel_id'], unique=False)
    op.create_index('idx_conversation_sessions_last_activity', 'conversation_sessions', ['session_last_activity_at'], unique=False)
    op.create_table('document_registry',
    sa.Column('document_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ingestion_job_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('doc_uid_base', sa.Text(), nullable=True),
    sa.Column('revision_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('document_name', sa.Text(), nullable=True),
    sa.Column('document_type', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Text(), nullable=True),
    sa.Column('source_authority', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.Text(), nullable=True),
    sa.Column('file_hash', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('extension', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('parser_version', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.Text(), nullable=True),
    sa.Column('detected_language_code', sa.Text(), nullable=True),
    sa.Column('publication_payload_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.job_id'], name=op.f('fk_document_registry_ingestion_job_id_ingestion_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('document_id', name=op.f('pk_document_registry'))
    )
    op.create_index('idx_document_registry_content_hash', 'document_registry', ['content_hash'], unique=False)
    op.create_index('idx_document_registry_doc_uid_base', 'document_registry', ['doc_uid_base'], unique=False)
    op.create_index('idx_document_registry_document_type', 'document_registry', ['document_type'], unique=False)
    op.create_index('idx_document_registry_file_hash', 'document_registry', ['file_hash'], unique=False)
    op.create_index('idx_document_registry_revision_date', 'document_registry', ['revision_date'], unique=False)
    op.create_index('idx_document_registry_source_authority', 'document_registry', ['source_authority'], unique=False)
    op.create_index('idx_document_registry_source_type', 'document_registry', ['source_type'], unique=False)
    op.create_index('idx_document_registry_status', 'document_registry', ['status'], unique=False)
    op.create_table('document_blocks',
    sa.Column('block_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('block_order', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.Text(), nullable=False),
    sa.Column('content_raw', sa.Text(), nullable=True),
    sa.Column('content_clean', sa.Text(), nullable=True),
    sa.Column('chapter', sa.Text(), nullable=True),
    sa.Column('section_number', sa.Text(), nullable=True),
    sa.Column('clause_number', sa.Text(), nullable=True),
    sa.Column('appendix_number', sa.Text(), nullable=True),
    sa.Column('table_number', sa.Text(), nullable=True),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('citation_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document_registry.document_id'], name=op.f('fk_document_blocks_document_id_document_registry'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('block_id', name=op.f('pk_document_blocks'))
    )
    op.create_index('idx_document_blocks_appendix_number', 'document_blocks', ['appendix_number'], unique=False)
    op.create_index('idx_document_blocks_block_order', 'document_blocks', ['document_id', 'block_order'], unique=False)
    op.create_index('idx_document_blocks_block_type', 'document_blocks', ['block_type'], unique=False)
    op.create_index('idx_document_blocks_document_id', 'document_blocks', ['document_id'], unique=False)
    op.create_index('idx_document_blocks_table_number', 'document_blocks', ['table_number'], unique=False)
    op.execute(
    """
    CREATE INDEX idx_document_blocks_embedding_hnsw
    ON document_blocks
    USING hnsw (embedding vector_cosine_ops)
    """
    )
    op.create_table('document_tables',
    sa.Column('table_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('table_number', sa.Text(), nullable=True),
    sa.Column('appendix_number', sa.Text(), nullable=True),
    sa.Column('table_type', sa.Text(), nullable=True),
    sa.Column('table_title', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('header_schema_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('rows_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('markdown_preview', sa.Text(), nullable=True),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('citation_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document_registry.document_id'], name=op.f('fk_document_tables_document_id_document_registry'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('table_id', name=op.f('pk_document_tables'))
    )
    op.create_index('idx_document_tables_appendix_number', 'document_tables', ['appendix_number'], unique=False)
    op.create_index('idx_document_tables_document_id', 'document_tables', ['document_id'], unique=False)
    op.create_index('idx_document_tables_table_number', 'document_tables', ['table_number'], unique=False)
    op.create_index('idx_document_tables_table_type', 'document_tables', ['table_type'], unique=False)
    op.create_table('legal_facts',
    sa.Column('fact_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('fact_type', sa.Text(), nullable=False),
    sa.Column('measure_code', sa.Text(), nullable=True),
    sa.Column('subject_category', sa.Text(), nullable=True),
    sa.Column('condition_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('validity_note', sa.Text(), nullable=True),
    sa.Column('citation_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document_registry.document_id'], name=op.f('fk_legal_facts_document_id_document_registry'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fact_id', name=op.f('pk_legal_facts'))
    )
    op.create_index('idx_legal_facts_document_id', 'legal_facts', ['document_id'], unique=False)
    op.create_index('idx_legal_facts_fact_type', 'legal_facts', ['fact_type'], unique=False)
    op.create_index('idx_legal_facts_measure_code', 'legal_facts', ['measure_code'], unique=False)
    op.create_index('idx_legal_facts_subject_category', 'legal_facts', ['subject_category'], unique=False)
    op.create_table('measure_aliases',
    sa.Column('alias_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('measure_code', sa.Text(), nullable=True),
    sa.Column('canonical_name', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("alias <> ''", name=op.f('ck_measure_aliases_chk_measure_aliases_alias_not_empty')),
    sa.ForeignKeyConstraint(['document_id'], ['document_registry.document_id'], name=op.f('fk_measure_aliases_document_id_document_registry'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alias_id', name=op.f('pk_measure_aliases')),
    sa.UniqueConstraint('document_id', 'alias', name='uq_measure_aliases_document_alias')
    )
    op.create_index('idx_measure_aliases_alias', 'measure_aliases', ['alias'], unique=False)
    op.create_index('idx_measure_aliases_document_id', 'measure_aliases', ['document_id'], unique=False)
    op.create_index('idx_measure_aliases_measure_code', 'measure_aliases', ['measure_code'], unique=False)
    op.create_table('question_events',
    sa.Column('question_event_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_text_raw', sa.Text(), nullable=False),
    sa.Column('question_text_normalized', sa.Text(), nullable=True),
    sa.Column('question_language_code', sa.Text(), server_default=sa.text("'ru'"), nullable=False),
    sa.Column('intent_type', postgresql.ENUM('ELIGIBILITY_QUESTION', 'DOCUMENTS_QUESTION', 'REJECTION_QUESTION', 'FORM_QUESTION', 'DEADLINE_QUESTION', 'PAYMENT_TIMING_QUESTION', 'AMOUNT_QUESTION', 'PROCEDURE_QUESTION', 'APPEAL_QUESTION', 'MIXED_QUESTION', 'AMBIGUOUS_QUESTION', 'NO_MEASURE_DETECTED', 'OTHER', name='question_intent_enum'), server_default=sa.text("'OTHER'"), nullable=False),
    sa.Column('measure_code', sa.Text(), nullable=True),
    sa.Column('subject_category_code', sa.Text(), nullable=True),
    sa.Column('query_constraints_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('routing_payload_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('classifier_version', sa.Text(), nullable=True),
    sa.Column('embedding_model_name', sa.Text(), nullable=True),
    sa.Column('question_embedding', Vector(1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.session_id'], name=op.f('fk_question_events_session_id_conversation_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_event_id', name=op.f('pk_question_events'))
    )
    op.create_index('idx_question_events_created_at', 'question_events', ['created_at'], unique=False)
    op.create_index('idx_question_events_intent', 'question_events', ['intent_type'], unique=False)
    op.create_index('idx_question_events_measure_code', 'question_events', ['measure_code'], unique=False)
    op.create_index('idx_question_events_session', 'question_events', ['session_id', 'created_at'], unique=False)
    op.create_table('answer_events',
    sa.Column('answer_event_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('question_event_id', sa.UUID(), nullable=False),
    sa.Column('answer_mode', postgresql.ENUM('DIRECT_STRUCTURED', 'GROUNDED_NARRATIVE', 'SAFE_NO_ANSWER', 'REUSED_ANSWER', name='answer_mode_enum'), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('answer_text_short', sa.Text(), nullable=True),
    sa.Column('answer_language_code', sa.Text(), server_default=sa.text("'ru'"), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('trust_score_at_generation', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('validation_status', postgresql.ENUM('PASSED', 'FAILED', 'PARTIAL', 'NOT_RUN', name='validation_status_enum'), server_default=sa.text("'NOT_RUN'"), nullable=False),
    sa.Column('deterministic_validation_passed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('semantic_validation_passed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('reuse_allowed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('reused_from_answer_event_id', sa.UUID(), nullable=True),
    sa.Column('reuse_policy_version', sa.Text(), nullable=True),
    sa.Column('reuse_decision_payload_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('citations_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('answer_payload_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('document_set_hash', sa.Text(), nullable=True),
    sa.Column('evidence_hash', sa.Text(), nullable=True),
    sa.Column('answer_payload_hash', sa.Text(), nullable=True),
    sa.Column('answer_text_hash', sa.Text(), nullable=True),
    sa.Column('generation_model_name', sa.Text(), nullable=True),
    sa.Column('generation_prompt_version', sa.Text(), nullable=True),
    sa.Column('pipeline_version', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)', name=op.f('ck_answer_events_chk_answer_events_confidence_range')),
    sa.CheckConstraint('trust_score_at_generation IS NULL OR (trust_score_at_generation >= 0 AND trust_score_at_generation <= 1)', name=op.f('ck_answer_events_chk_answer_events_trust_range')),
    sa.ForeignKeyConstraint(['question_event_id'], ['question_events.question_event_id'], name=op.f('fk_answer_events_question_event_id_question_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reused_from_answer_event_id'], ['answer_events.answer_event_id'], name=op.f('fk_answer_events_reused_from_answer_event_id_answer_events'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('answer_event_id', name=op.f('pk_answer_events'))
    )
    op.create_index('idx_answer_events_created_at', 'answer_events', ['created_at'], unique=False)
    op.create_index('idx_answer_events_document_set_hash', 'answer_events', ['document_set_hash'], unique=False)
    op.create_index('idx_answer_events_evidence_hash', 'answer_events', ['evidence_hash'], unique=False)
    op.create_index('idx_answer_events_question', 'answer_events', ['question_event_id'], unique=False)
    op.create_index('idx_answer_events_reuse_allowed', 'answer_events', ['reuse_allowed'], unique=False)
    op.create_index('idx_answer_events_reused_from', 'answer_events', ['reused_from_answer_event_id'], unique=False)
    op.create_index('idx_answer_events_validation_status', 'answer_events', ['validation_status'], unique=False)
    op.create_table('document_table_rows',
    sa.Column('row_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=True),
    sa.Column('row_order', sa.Integer(), nullable=False),
    sa.Column('row_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('normalized_row_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('row_summary', sa.Text(), nullable=True),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('citation_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document_registry.document_id'], name=op.f('fk_document_table_rows_document_id_document_registry'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['document_tables.table_id'], name=op.f('fk_document_table_rows_table_id_document_tables'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('row_id', name=op.f('pk_document_table_rows'))
    )
    op.create_index('idx_document_table_rows_document_id', 'document_table_rows', ['document_id'], unique=False)
    op.create_index('idx_document_table_rows_row_order', 'document_table_rows', ['table_id', 'row_order'], unique=False)
    op.create_index('idx_document_table_rows_table_id', 'document_table_rows', ['table_id'], unique=False)
    op.create_table('answer_evidence_items',
    sa.Column('answer_evidence_item_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('answer_event_id', sa.UUID(), nullable=False),
    sa.Column('evidence_order', sa.Integer(), nullable=False),
    sa.Column('evidence_item_type', postgresql.ENUM('DOCUMENT', 'BLOCK', 'TABLE', 'TABLE_ROW', 'LEGAL_FACT', name='evidence_item_type_enum'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('block_id', sa.UUID(), nullable=True),
    sa.Column('table_id', sa.UUID(), nullable=True),
    sa.Column('table_row_id', sa.UUID(), nullable=True),
    sa.Column('legal_fact_id', sa.UUID(), nullable=True),
    sa.Column('citation_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('document_file_hash', sa.Text(), nullable=True),
    sa.Column('document_content_hash', sa.Text(), nullable=True),
    sa.Column('role_code', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('\n            ((CASE WHEN document_id IS NOT NULL THEN 1 ELSE 0 END) +\n             (CASE WHEN block_id IS NOT NULL THEN 1 ELSE 0 END) +\n             (CASE WHEN table_id IS NOT NULL THEN 1 ELSE 0 END) +\n             (CASE WHEN table_row_id IS NOT NULL THEN 1 ELSE 0 END) +\n             (CASE WHEN legal_fact_id IS NOT NULL THEN 1 ELSE 0 END)) = 1\n            ', name=op.f('ck_answer_evidence_items_chk_answer_evidence_exactly_one_pointer')),
    sa.ForeignKeyConstraint(['answer_event_id'], ['answer_events.answer_event_id'], name=op.f('fk_answer_evidence_items_answer_event_id_answer_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('answer_evidence_item_id', name=op.f('pk_answer_evidence_items')),
    sa.UniqueConstraint('answer_event_id', 'evidence_order', name='uq_answer_evidence_items_order')
    )
    op.create_index('idx_answer_evidence_items_answer', 'answer_evidence_items', ['answer_event_id'], unique=False)
    op.create_index('idx_answer_evidence_items_doc_content_hash', 'answer_evidence_items', ['document_content_hash'], unique=False)
    op.create_index('idx_answer_evidence_items_document', 'answer_evidence_items', ['document_id'], unique=False)
    op.create_index('idx_answer_evidence_items_fact', 'answer_evidence_items', ['legal_fact_id'], unique=False)
    op.create_index('idx_answer_evidence_items_table', 'answer_evidence_items', ['table_id'], unique=False)
    op.create_table('answer_feedback',
    sa.Column('feedback_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('answer_event_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('reason_code', postgresql.ENUM('CORRECT_AND_HELPFUL', 'PARTIALLY_HELPFUL', 'NOT_RELEVANT', 'INCORRECT_FACTS', 'OUTDATED_INFORMATION', 'UNCLEAR_ANSWER', 'TOO_LONG', 'TOO_SHORT', 'MISSING_DETAILS', 'WRONG_DOCUMENTS_USED', 'OTHER', name='feedback_reason_code_enum'), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('feedback_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('is_sampled_request', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('sampling_policy_version', sa.Text(), nullable=True),
    sa.Column('is_resolved_for_analytics', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint('score >= 1 AND score <= 5', name=op.f('ck_answer_feedback_chk_answer_feedback_score_range')),
    sa.ForeignKeyConstraint(['answer_event_id'], ['answer_events.answer_event_id'], name=op.f('fk_answer_feedback_answer_event_id_answer_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feedback_channel_id'], ['channels.channel_id'], name=op.f('fk_answer_feedback_feedback_channel_id_channels'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.session_id'], name=op.f('fk_answer_feedback_session_id_conversation_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id', name=op.f('pk_answer_feedback')),
    sa.UniqueConstraint('session_id', 'answer_event_id', name='uq_answer_feedback_one_vote_per_session_answer')
    )
    op.create_index('idx_answer_feedback_answer', 'answer_feedback', ['answer_event_id'], unique=False)
    op.create_index('idx_answer_feedback_score', 'answer_feedback', ['score'], unique=False)
    op.create_index('idx_answer_feedback_session', 'answer_feedback', ['session_id'], unique=False)
    op.create_index('idx_answer_feedback_submitted_at', 'answer_feedback', ['submitted_at'], unique=False)
    op.create_table('answer_reuse_candidates',
    sa.Column('reuse_candidate_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_answer_event_id', sa.UUID(), nullable=False),
    sa.Column('reuse_status', postgresql.ENUM('ELIGIBLE', 'TEMPORARILY_BLOCKED', 'BLOCKED', 'NEEDS_REVALIDATION', name='reuse_status_enum'), server_default=sa.text("'NEEDS_REVALIDATION'"), nullable=False),
    sa.Column('reuse_allowed_effective', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('avg_feedback_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('feedback_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('negative_feedback_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('reuse_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('last_revalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revalidation_payload_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('block_reason_code', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('avg_feedback_score IS NULL OR (avg_feedback_score >= 1 AND avg_feedback_score <= 5)', name=op.f('ck_answer_reuse_candidates_chk_answer_reuse_candidates_avg_feedback_range')),
    sa.CheckConstraint('reuse_score IS NULL OR (reuse_score >= 0 AND reuse_score <= 1)', name=op.f('ck_answer_reuse_candidates_chk_answer_reuse_candidates_reuse_score_range')),
    sa.ForeignKeyConstraint(['source_answer_event_id'], ['answer_events.answer_event_id'], name=op.f('fk_answer_reuse_candidates_source_answer_event_id_answer_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reuse_candidate_id', name=op.f('pk_answer_reuse_candidates')),
    sa.UniqueConstraint('source_answer_event_id', name=op.f('uq_answer_reuse_candidates_source_answer_event_id'))
    )
    op.create_index('idx_answer_reuse_candidates_allowed', 'answer_reuse_candidates', ['reuse_allowed_effective'], unique=False)
    op.create_index('idx_answer_reuse_candidates_reuse_score', 'answer_reuse_candidates', ['reuse_score'], unique=False)
    op.create_index('idx_answer_reuse_candidates_status', 'answer_reuse_candidates', ['reuse_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_answer_reuse_candidates_status', table_name='answer_reuse_candidates')
    op.drop_index('idx_answer_reuse_candidates_reuse_score', table_name='answer_reuse_candidates')
    op.drop_index('idx_answer_reuse_candidates_allowed', table_name='answer_reuse_candidates')
    op.drop_table('answer_reuse_candidates')
    op.drop_index('idx_answer_feedback_submitted_at', table_name='answer_feedback')
    op.drop_index('idx_answer_feedback_session', table_name='answer_feedback')
    op.drop_index('idx_answer_feedback_score', table_name='answer_feedback')
    op.drop_index('idx_answer_feedback_answer', table_name='answer_feedback')
    op.drop_table('answer_feedback')
    op.drop_index('idx_answer_evidence_items_table', table_name='answer_evidence_items')
    op.drop_index('idx_answer_evidence_items_fact', table_name='answer_evidence_items')
    op.drop_index('idx_answer_evidence_items_document', table_name='answer_evidence_items')
    op.drop_index('idx_answer_evidence_items_doc_content_hash', table_name='answer_evidence_items')
    op.drop_index('idx_answer_evidence_items_answer', table_name='answer_evidence_items')
    op.drop_table('answer_evidence_items')
    op.drop_index('idx_document_table_rows_table_id', table_name='document_table_rows')
    op.drop_index('idx_document_table_rows_row_order', table_name='document_table_rows')
    op.drop_index('idx_document_table_rows_document_id', table_name='document_table_rows')
    op.drop_table('document_table_rows')
    op.drop_index('idx_answer_events_validation_status', table_name='answer_events')
    op.drop_index('idx_answer_events_reused_from', table_name='answer_events')
    op.drop_index('idx_answer_events_reuse_allowed', table_name='answer_events')
    op.drop_index('idx_answer_events_question', table_name='answer_events')
    op.drop_index('idx_answer_events_evidence_hash', table_name='answer_events')
    op.drop_index('idx_answer_events_document_set_hash', table_name='answer_events')
    op.drop_index('idx_answer_events_created_at', table_name='answer_events')
    op.drop_table('answer_events')
    op.drop_index('idx_question_events_session', table_name='question_events')
    op.drop_index('idx_question_events_measure_code', table_name='question_events')
    op.drop_index('idx_question_events_intent', table_name='question_events')
    op.drop_index('idx_question_events_created_at', table_name='question_events')
    op.drop_table('question_events')
    op.drop_index('idx_measure_aliases_measure_code', table_name='measure_aliases')
    op.drop_index('idx_measure_aliases_document_id', table_name='measure_aliases')
    op.drop_index('idx_measure_aliases_alias', table_name='measure_aliases')
    op.drop_table('measure_aliases')
    op.drop_index('idx_legal_facts_subject_category', table_name='legal_facts')
    op.drop_index('idx_legal_facts_measure_code', table_name='legal_facts')
    op.drop_index('idx_legal_facts_fact_type', table_name='legal_facts')
    op.drop_index('idx_legal_facts_document_id', table_name='legal_facts')
    op.drop_table('legal_facts')
    op.drop_index('idx_document_tables_table_type', table_name='document_tables')
    op.drop_index('idx_document_tables_table_number', table_name='document_tables')
    op.drop_index('idx_document_tables_document_id', table_name='document_tables')
    op.drop_index('idx_document_tables_appendix_number', table_name='document_tables')
    op.drop_table('document_tables')
    op.execute("DROP INDEX IF EXISTS idx_document_blocks_embedding_hnsw")
    op.drop_index('idx_document_blocks_table_number', table_name='document_blocks')
    op.drop_index('idx_document_blocks_document_id', table_name='document_blocks')
    op.drop_index('idx_document_blocks_block_type', table_name='document_blocks')
    op.drop_index('idx_document_blocks_block_order', table_name='document_blocks')
    op.drop_index('idx_document_blocks_appendix_number', table_name='document_blocks')
    op.drop_table('document_blocks')
    op.drop_index('idx_document_registry_status', table_name='document_registry')
    op.drop_index('idx_document_registry_source_type', table_name='document_registry')
    op.drop_index('idx_document_registry_source_authority', table_name='document_registry')
    op.drop_index('idx_document_registry_revision_date', table_name='document_registry')
    op.drop_index('idx_document_registry_file_hash', table_name='document_registry')
    op.drop_index('idx_document_registry_document_type', table_name='document_registry')
    op.drop_index('idx_document_registry_doc_uid_base', table_name='document_registry')
    op.drop_index('idx_document_registry_content_hash', table_name='document_registry')
    op.drop_table('document_registry')
    op.drop_index('idx_conversation_sessions_last_activity', table_name='conversation_sessions')
    op.drop_index('idx_conversation_sessions_channel', table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    op.drop_index('idx_quality_aggregates_daily_measure', table_name='quality_aggregates_daily')
    op.drop_index('idx_quality_aggregates_daily_date', table_name='quality_aggregates_daily')
    op.drop_table('quality_aggregates_daily')
    op.drop_index('idx_ingestion_jobs_status', table_name='ingestion_jobs')
    op.drop_index('idx_ingestion_jobs_started_at', table_name='ingestion_jobs')
    op.drop_index('idx_ingestion_jobs_stage', table_name='ingestion_jobs')
    op.drop_index('idx_ingestion_jobs_file_hash', table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_table('channels')
    # ### end Alembic commands ###